http://eshare.stust.edu.tw/EshareFile/2011_10/2011_10_f2c636fa.pdf

In [1]:
import numpy as np
from scipy.optimize import linprog

In [2]:
c = [-1, -1.2]
A_ub = [[2, 1], 
        [1, 3]]
b_ub = [180, 300]
x0_b = [0, None]
x1_b = [0, None]

In [3]:
res = linprog(c,
              A_ub=A_ub, 
              b_ub=b_ub, 
              bounds=(x0_b, x1_b), 
              options={"disp": True})

Optimization terminated successfully.
         Current function value: -148.800000 
         Iterations: 2


In [4]:
c = [-1, -1.2, 0, 0]
A_eq = [[2, 1, 1, 0], 
        [1, 3, 0, 1]]
b_eq = [180, 300]
x0_b = [0, None]
x1_b = [0, None]
x2_b = [0, None]
x3_b = [0, None]

In [5]:
res = linprog(c,
              A_eq=A_eq, 
              b_eq=b_eq, 
              bounds=(x0_b, x1_b, x2_b, x3_b), 
              options={"disp": True})

Optimization terminated successfully.
         Current function value: -148.800000 
         Iterations: 2


In [6]:
def myLinprog(c,
              A_eq=None,
              b_eq=None):
    '''
    亂寫
    '''
    pass

In [12]:
# 單一解
# c = [-1, -1.2, 0, 0]
# c = np.array(c).astype(np.float)

# A_eq = [[2, 1, 1, 0], 
#         [1, 3, 0, 1]]
# A_eq = np.array(A_eq).astype(np.float)

# b_eq = [180, 300]
# b_eq = np.array(b_eq).astype(np.float)

# ans = 0

# unbounded解
# c = [-3, -2, 0, 0]
# c = np.array(c).astype(np.float)

# A_eq = [[1, -1, 1, 0], 
#         [1, 0, 0, 1]]
# A_eq = np.array(A_eq).astype(np.float)

# b_eq = [3, 2]
# b_eq = np.array(b_eq).astype(np.float)

# ans = 0

# 無限多解
c = [-4, -2, 0, 0]
c = np.array(c).astype(np.float)

A_eq = [[1, 1, 1, 0], 
        [2, 1, 0, 1]]
A_eq = np.array(A_eq).astype(np.float)

b_eq = [8, 10]
b_eq = np.array(b_eq).astype(np.float)

ans = 0

# 無解還沒測試

while c.min() < 0:
    
    index_var = c.argmin()
    print('發現 index:', index_var, 'value:', c.min())
    
    ratios = []
    for eq in range(b_eq.shape[0]):
        if A_eq[eq, index_var] != 0:
            ratios.append(b_eq[eq] / A_eq[eq, index_var])
    print('所有的 ratio:', ratios)
    
    try:
        ratio = min(v for v in ratios if v > 0)
    except:
        print('unbounded')
        break
    
    index_eq = np.where( ratios==ratio )[0][0]
    print('使用代換的eq:', index_eq)
    
    scale = 1 / A_eq[index_eq, index_var]
    A_eq[index_eq, :] = A_eq[index_eq, :] * scale 
    b_eq[index_eq] = b_eq[index_eq] * scale 
    print('調整倍數:\n', A_eq)
    print('調整倍數:', b_eq)
    
    for eq in range(A_eq.shape[0]):
        if eq != index_eq:
            scale = A_eq[eq, index_var]
            A_eq[eq, :] = A_eq[eq, :] - A_eq[index_eq, :] * scale
            b_eq[eq] = b_eq[eq] - b_eq[index_eq]* scale
            
    print('加減消去:\n', A_eq)
    print('加減消去:', b_eq)
    
    scale = c[index_var]
    c = c - scale * A_eq[index_eq]
    ans = ans - scale * b_eq[index_eq]
    print('加減消去:', c)
    print('目前累計:', -ans)
    print('=====.=====.=====.=====')
    
print('答案:', -ans)

發現 index: 0 value: -4.0
所有的 ratio: [8.0, 5.0]
使用代換的eq: 1
調整倍數:
 [[ 1.   1.   1.   0. ]
 [ 1.   0.5  0.   0.5]]
調整倍數: [ 8.  5.]
加減消去:
 [[ 0.   0.5  1.  -0.5]
 [ 1.   0.5  0.   0.5]]
加減消去: [ 3.  5.]
加減消去: [ 0.  0.  0.  2.]
目前累計: -20.0
=====.=====.=====.=====
答案: -20.0
