http://cpmarkchang.logdown.com/posts/278457-neural-network-recurrent-neural-network

In [7]:
from math import e                                                                                    
import numpy as np

def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

def max_one(x):
    return  (x == x.max()).astype(float)

def rnn(x):
    
    r = 0.05
    dim = x.shape[1]
    w_p = np.random.rand(dim) - 0.5
    w_c = np.random.rand(dim) - 0.5
    w_b = np.random.rand(dim) - 0.5
    
    l = x.shape[0]
    n_in = np.zeros((l, dim))
    n_out = np.zeros((l, dim))
    
    for h in range(10000):
        
        #feedforward
        for i in range(l - 1): 
            n_in[i] = w_c * x[i] + w_p * n_out[i] + w_b
            n_out[i + 1] = sigmoid(n_in[i])
            
        #backpropagation
        for i in range(l - 1): 
            for j in range(i + 1):
                k =  i - j
                
                if j == 0:
                    d_c = n_out[k + 1] - x[k + 1]
                else:
                    d_c = w_p * n_out[k + 1] * (1 - n_out[k + 1]) * d_c
                    
                w_c = w_c - r * d_c * x [k]
                w_b = w_b - r * d_c
                w_p = w_p - r * d_c * n_out[k]
    
    #測試輸出
    for i in range(l - 1):
        n_in[i] = w_c * x[i] + w_p * n_out[i] + w_b
        n_out[i + 1] = sigmoid(n_in[i])
        
    for x, w in zip(x,n_out):
        print x, max_one(w)

In [8]:
np.random.seed(0)

# 預計 n 個字詞 輪流出現 a b c a b c a b c ...

n = 5
loop = 3
x = np.zeros((n * loop, n))

for index_loop in range(loop):
    for index_n in range(n):
        x[index_loop * n + index_n, index_n] = 1

rnn(x)

[ 1.  0.  0.  0.  0.] [ 1.  1.  1.  1.  1.]
[ 0.  1.  0.  0.  0.] [ 0.  1.  0.  0.  0.]
[ 0.  0.  1.  0.  0.] [ 0.  0.  1.  0.  0.]
[ 0.  0.  0.  1.  0.] [ 0.  0.  0.  0.  1.]
[ 0.  0.  0.  0.  1.] [ 0.  0.  0.  0.  1.]
[ 1.  0.  0.  0.  0.] [ 1.  0.  0.  0.  0.]
[ 0.  1.  0.  0.  0.] [ 0.  1.  0.  0.  0.]
[ 0.  0.  1.  0.  0.] [ 0.  0.  1.  0.  0.]
[ 0.  0.  0.  1.  0.] [ 0.  0.  0.  1.  0.]
[ 0.  0.  0.  0.  1.] [ 0.  0.  0.  0.  1.]
[ 1.  0.  0.  0.  0.] [ 1.  0.  0.  0.  0.]
[ 0.  1.  0.  0.  0.] [ 0.  1.  0.  0.  0.]
[ 0.  0.  1.  0.  0.] [ 0.  0.  1.  0.  0.]
[ 0.  0.  0.  1.  0.] [ 0.  0.  0.  1.  0.]
[ 0.  0.  0.  0.  1.] [ 0.  0.  0.  0.  1.]
