In [13]:
%matplotlib inline
import matplotlib as plt
import numpy as np
from scipy import linalg
import cv2

In [14]:
M2 = np.asarray([[2, 0], [0 , 2]], np.float32)
retval, M5 = cv2.invert(M2)
print M5

[[ 0.5 -0. ]
 [-0.   0.5]]


In [15]:
?linalg.lstsq

In [19]:
x = np.array([1, 2, 3, 4])
y = np.array([6, 5, 7, 10])
A = np.vstack([np.ones(len(x)), x]).T
print A

[[ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]]


In [24]:
k1, k2 = np.linalg.lstsq(A, y)[0]
print k1, k2
?np.linalg.lstsq

3.5 1.4


In [28]:
p1 = np.array([1, 2, 2])
p2 = np.array([3, 5, 3])
p3 = np.array([5, 1, 8])
y = np.array([10, 8, 3])
A = np.vstack([p1, p2, p3]).T
print A

[[1 3 5]
 [2 5 1]
 [2 3 8]]


In [29]:
print np.linalg.lstsq(A, y)[0]

[-9.28  5.16  0.76]


In [40]:
p1 = np.float32([[10,10], [10,50], [50,10]])#原圖三個點
p2 = np.float32([[50,50], [50,90], [90,50]])#移至三個點

m = cv2.getAffineTransform(p1, p2)
print m

y  = np.array([50, 50, 50, 90, 90, 50])
p0 = np.array([10,  0, 10,  0, 50,  0])
p1 = np.array([10,  0, 50,  0, 10,  0])
p2 = np.array([ 1,  0,  1,  0,  1,  0])
p3 = np.array([ 0, 10,  0, 10,  0, 50])
p4 = np.array([ 0, 10,  0, 50,  0, 10])
p5 = np.array([ 0,  1,  0,  1,  0,  1])

A = np.vstack([p0, p1, p2, p3, p4, p5]).T
print A
print y

ans = np.reshape(np.linalg.lstsq(A, y)[0], (2, 3))
#ans = ans.astype(np.uint8)
print ans

[[  1.   0.  40.]
 [  0.   1.  40.]]
[[10 10  1  0  0  0]
 [ 0  0  0 10 10  1]
 [10 50  1  0  0  0]
 [ 0  0  0 10 50  1]
 [50 10  1  0  0  0]
 [ 0  0  0 50 10  1]]
[50 50 50 90 90 50]
[[  1.00000000e+00   0.00000000e+00   4.00000000e+01]
 [ -1.77635684e-15   1.00000000e+00   4.00000000e+01]]


In [43]:
y  = np.array([50, 50, 90])
p0 = np.array([10, 10, 50])
p1 = np.array([10, 50, 10])
p2 = np.array([ 1,  1,  1])

A = np.vstack([p0, p1, p2]).T
print A
print y
ans = np.reshape(np.linalg.lstsq(A, y)[0], (1, 3))
print ans

y  = np.array([50, 90, 50])
p0 = np.array([10, 10, 50])
p1 = np.array([10, 50, 10])
p2 = np.array([ 1,  1,  1])

A = np.vstack([p0, p1, p2]).T
print A
print y
ans = np.reshape(np.linalg.lstsq(A, y)[0], (1, 3))
print ans

[[10 10  1]
 [10 50  1]
 [50 10  1]]
[50 50 90]
[[  1.   0.  40.]]
[[10 10  1]
 [10 50  1]
 [50 10  1]]
[50 90 50]
[[ -2.73488027e-16   1.00000000e+00   4.00000000e+01]]
